---
- name: Includes dynamic configuration file
  include_vars: "{{ vars_files }}"
  when: vars_files is defined

- name: mount_network_fs | Install base packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - nfs-common

- name: mount_network_fs | Mount for ubuntu trusty 14.04
  include: configure-ubuntu-trusty.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

- name: mount_network_fs | Mount for ubuntu not trusty
  include: configure-ubuntu-others.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'trusty'
